# -*- coding: utf-8 -*-
#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.

version: "3.2"

services:
  web:
    restart: "always"
    build: .
    command: /bin/bash -c "rm -f /code/celeryd.pid; celery worker -A invenio_app.celery --loglevel=INFO -B -D && uwsgi --ini /code/scripts/uwsgi.ini"
    environment:
      - PATH=/home/invenio/.virtualenvs/invenio/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
      - INVENIO_WEB_HOST=127.0.0.1
      - INVENIO_WEB_INSTANCE=invenio
      - INVENIO_WEB_VENV=invenio
      - INVENIO_USER_EMAIL=info@inveniosoftware.org
      - INVENIO_USER_PASS=uspass123
      - INVENIO_POSTGRESQL_HOST=postgresql
      - INVENIO_POSTGRESQL_DBNAME=invenio
      - INVENIO_POSTGRESQL_DBUSER=invenio
      - INVENIO_POSTGRESQL_DBPASS=dbpass123
      - INVENIO_REDIS_HOST=redis
      - INVENIO_ELASTICSEARCH_HOST=elasticsearch
      - INVENIO_RABBITMQ_HOST=rabbitmq
      - INVENIO_WORKER_HOST=127.0.0.1
      - INVENIO_FILES_LOCATION_NAME=local
      - INVENIO_FILES_LOCATION_URI=/var/tmp
      - INVENIO_ROLE_SYSTEM=System Administrator
      - INVENIO_ROLE_REPOSITORY=Repository Administrator
      - INVENIO_ROLE_CONTRIBUTOR=Contributor
      - INVENIO_ROLE_COMMUNITY=Community Administrator
      - FLASK_DEBUG=0
      - SEARCH_INDEX_PREFIX=tenant1
    volumes:
      - weko3_data:/var/tmp
      - static_data:/home/invenio/.virtualenvs/invenio/var/instance/static
      - type: bind
        source: .
        target: /code
      - /code/modules/invenio-files-rest/invenio_files_rest.egg-info
      - /code/modules/invenio-s3/invenio_s3.egg-info
      - /code/modules/invenio-oaiharvester/invenio_oaiharvester.egg-info
      - /code/modules/invenio-oaiserver/invenio_oaiserver.egg-info
      - /code/modules/invenio-records/invenio_records.egg-info
      - /code/modules/invenio-previewer/invenio_previewer.egg-info
      - /code/modules/invenio-stats/invenio_stats.egg-info
      - /code/modules/invenio-records-rest/invenio_records_rest.egg-info
      - /code/modules/invenio-communities/invenio_communities.egg-info
      - /code/modules/invenio-mail/invenio_mail.egg-info
      - /code/modules/invenio-deposit/invenio_deposit.egg-info
      - /code/modules/invenio-resourcesyncserver/invenio_resourcesyncserver.egg-info
      - /code/modules/invenio-resourcesyncclient/invenio_resourcesyncclient.egg-info
      - /code/modules/weko-theme/weko_theme.egg-info
      - /code/modules/weko-itemtypes-ui/weko_itemtypes_ui.egg-info
      - /code/modules/weko-items-ui/weko_items_ui.egg-info
      - /code/modules/weko-accounts/weko_accounts.egg-info
      - /code/modules/weko-admin/weko_admin.egg-info
      - /code/modules/weko-logging/weko_logging.egg-info
      - /code/modules/weko-gridlayout/weko_gridlayout.egg-info
      - /code/modules/weko-groups/weko_groups.egg-info
      - /code/modules/weko-search-ui/weko_search_ui.egg-info
      - /code/modules/weko-records/weko_records.egg-info
      - /code/modules/weko-records-ui/weko_records_ui.egg-info
      - /code/modules/weko-schema-ui/weko_schema_ui.egg-info
      - /code/modules/weko-index-tree/weko_index_tree.egg-info
      - /code/modules/weko-user-profiles/weko_user_profiles.egg-info
      - /code/modules/weko-deposit/weko_deposit.egg-info
      - /code/modules/weko-authors/weko_authors.egg-info
      - /code/modules/weko-handle/weko_handle.egg-info
      - /code/modules/weko-workflow/weko_workflow.egg-info
      - /code/modules/weko-indextree-journal/weko_indextree_journal.egg-info
      - /code/modules/weko-bulkupdate/weko_bulkupdate.egg-info
      - /code/modules/weko-items-autofill/weko_items_autofill.egg-info
      - /code/modules/weko-sitemap/weko_sitemap.egg-info
    user: invenio
    links:
      - postgresql
      - redis
      - elasticsearch
      - rabbitmq
    ports:
      - "5001:5000"

  postgresql:
    restart: "always"
    image: postgres:12
    environment:
      - POSTGRES_USER=invenio
      - POSTGRES_DB=invenio
      - POSTGRES_PASSWORD=dbpass123
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    ports:
      - "25401:5432"

  redis:
    restart: "always"
    image: redis
    ports:
      - "26301:6379"

  elasticsearch:
    restart: "always"
    build:
      context: .
      dockerfile: ./elasticsearch/Dockerfile
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "29201:9200"
      - "29301:9300"

  rabbitmq:
    restart: "always"
    image: rabbitmq
    ports:
      - "24301:4369"
      - "45601:25672"

  nginx:
    restart: "always"
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_data:/home/invenio/.virtualenvs/invenio/var/instance/static
    links:
      - web

  flower:
    restart: "always"
    image: mher/flower
    command: --broker=amqp://guest:guest@rabbitmq:5672// --broker_api=http://guest:guest@rabbitmq:5671/api/
    ports:
      - "5501:5555"
    links:
      - rabbitmq

  kibana:
    build:
      context: .
      dockerfile: ./kibana/Dockerfile
    restart: "always"
    command: kibana
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    links:
      - elasticsearch

  handle:
    image: handle_svr
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "2641:2641/udp"
      - "2641:2641/tcp"
      - "8000:8000/tcp"
    environment:
      SERVER_ADMINS: '300:200/23'
      REPLICATION_ADMINS: '300:200/23'
      ALLOW_RECURSION: 'yes'
      SERVER_PRIVATE_KEY_PEM: "-----BEGIN PRIVATE KEY-----\r\nMIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQDvNoc+4J/rqxR5\r\niXFqt2W2qanBsrQpeXFd/yfIG07iGu1zzd77CD699+RTEUNbu3zS3ELNVF8QpmrX\r\neqQt7wVB7drA5wKvonTsQuOvYNnBhuS0UOl2lfF1J2wsKQ8mCkCL723QBTjcEkUi\r\nw/gAtaoDcSsnK+XjflWNcDaPrEaCjl0c3xdw4pAyt1316adPDOT1w96P52ki53U4\r\nje6Zfn3ZI2LSVrooHcNA/XRfgSXqa5n3aFlyrla7bIHk/kMtkBWzTWNF/wQbcqpn\r\nbkQrj3mVVyLby7hKv+J4KyNDYfIffSnDVtoegMTyflj/oocNkKM9H0y+3zSuNLdu\r\ng9zu57V/AgMBAAECggEBAOQMKdcpsYusZzKOcw93k4IWMP217cd0PT2NGFHOpt8r\r\nKKAz7ZWIALh98K+4T2zOSmuDDDRPcOmgnU6bXpVjvrFhniA0mvzxdWIfSoxRWocC\r\noFm+oTMqMyyqzpcy9XwgXfSJ5zhfIhu7VymThYS3q0LoymjnkpvUPp8+EOXbKMUg\r\nN3CDtODY1FpPgWUSUWh1wAeUgn748xbg5Fisa3UMf8Ykhg3qoInbmcOy6FyimGe6\r\na+2tv2oEKNPD+EsqoZk3azsq5uSigPplK/WBV6W3jsEEeVbOGt7LbxyLTQ/1AjNQ\r\nKsbH7adlNebvCaiOMFZnYSR0AutM3+QcebaxWnmYTQECgYEA/W5Tnui1QiCdcpXz\r\nP8GKV/vL2ohdutrqWktujPQPQWRVFikJ9tkGxcjZGdotBNq2PkDBZ+mm7ufzumgy\r\n1aNmNx4mTcPiXIziMDSJ6/vzNKDTEVsJwrtZOY9WuRjq5FjMjIB3XlsJzB/VRNML\r\nZ7VujTYzas70voLmRndYFKCAOr8CgYEA8aNOD5PpymQAYqhAMo2i5u83BIgNYWn0\r\n4XUSlJqswHTzv9BlFV7bL3YCMnMftdzdLbkviAbv14GaBHgaduQEK9EnsslPwmho\r\nis6bGAg2ciwSekTyCjlWS4VLASbG7b/L5yR1eP8WUPEgDLoI3zmd1r8v1k2iJztk\r\nNz6AzLHg9UECgYEA2EfhgUpj9k1TUUj7UTvgzvmKnbOnGiJdwjWB4TUgF9SCcOkR\r\nIeNRTlX8QX3a0bu9sB8fb4kN9/FoJXtrdrt+LifC1LcJZaauGimcUxKwGgfuWW9y\r\nQwgUO3VCs7C6Nao61uWD+biEAfpgzd22bAmAkW7iLpL0d+nKj/Sl7OSUyo0CgYEA\r\nwJ1tbyt39FYsnHgD3Ihcr3tGPv14tQsyIboh2oVFaZCQcHlc6mEXlUibTb3JLD3n\r\nrTft9J+a9g2gSSm35sexr3/lBjZEtvJlSyiQJuL9C5uoCwEEczPrXv3coQlZD1GQ\r\n5yp/3bhxAIqFAsAUrGQQNotmRYzS0jUcmJDhOMoeSUECgYEA5l/oF45oWA7en52R\r\no5MLPhyJFZ7HXVvh/7Aq19cCxZzTsx/zMqHyEMElUXWE/fxtHyQ1cyWtf3mlmsC6\r\nqyBmVy+sd7YIcmjBPPKWg/vGp9VY3EyzCCj/c3JPHjTMgdDHc1G2g1+sOYDhqvmX\r\njyoPDCUzCrxX1D3FgXj938gw5aE=\r\n-----END PRIVATE KEY-----"
      SERVER_PUBLIC_KEY_PEM: "-----BEGIN PUBLIC KEY-----\r\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7zaHPuCf66sUeYlxardl\r\ntqmpwbK0KXlxXf8nyBtO4hrtc83e+wg+vffkUxFDW7t80txCzVRfEKZq13qkLe8F\r\nQe3awOcCr6J07ELjr2DZwYbktFDpdpXxdSdsLCkPJgpAi+9t0AU43BJFIsP4ALWq\r\nA3ErJyvl435VjXA2j6xGgo5dHN8XcOKQMrdd9emnTwzk9cPej+dpIud1OI3umX59\r\n2SNi0la6KB3DQP10X4El6muZ92hZcq5Wu2yB5P5DLZAVs01jRf8EG3KqZ25EK495\r\nlVci28u4Sr/ieCsjQ2HyH30pw1baHoDE8n5Y/6KHDZCjPR9Mvt80rjS3boPc7ue1\r\nfwIDAQAB\r\n-----END PUBLIC KEY-----"
    links:
      - web

volumes:
  weko3_data:
  static_data:
  pgsql-data:
  es-data:
